name: unit-tests
on:
  push:
    branches: [ main ]
  
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Install Ninja
      run: brew upgrade && brew install ninja

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0
      
    - name: Create default profile
      run: conan profile new default --detect
      
    - name: Install dependencies
      run: conan install . -s build_type=${{env.BUILD_TYPE}}
      
    - name: Configure CMake
      run: cmake . -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
    - name: Build
      run: cmake --build .
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
