name: unit-tests
on:
  push:
    branches: [ multi_platform_builds ]
  
env:
  BUILD_TYPE: Release
jobs:
  build:
    strategy:
      matrix:
        os: [macos-10.15, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0
      
    - name: Create default profile
      run: conan profile new default --detect
      
    - name: Install dependencies
      run: conan install . -s build_type=${{env.BUILD_TYPE}}

    - name: Configure CMake Windows
      if: ${{ env.RUNNER_OS == 'Windows' }}
      run:
        cmake -G "Visual Studio 16 2019" -A x64 . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Configure CMake Mac
      if: ${{ env.RUNNER_OS == 'macOS' }}
      run:
        cmake . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
    - name: Build
      run: cmake --build .
      
    - name: Test
      working-directory: ${{github.workspace}}
      run: ctest -C ${{env.BUILD_TYPE}}
